from .logger import logger as logger
from _typeshed import Incomplete

class Ipc:
    ENCODING: str
    BUFFER_SIZE: int
    TIMEOUT: int
    pipe_name: str
    sa: Incomplete
    pipe: Incomplete
    pipe_mode: str
    connected: bool
    lock: Incomplete
    r_lock: Incomplete
    def __init__(self, pipe_name=None) -> None: ...
    def create_master_pipe(self) -> None: ...
    def create_slave_pipe(self) -> None: ...
    def write(self, msg: str): ...
    @property
    def read(self) -> str: ...
    def clear(self) -> None: ...
    def close(self) -> None: ...
