import threading
import types
from ..core.ipc import Ipc as Ipc
from .base import TerminalIn as TerminalIn, TerminalOut as TerminalOut
from _typeshed import Incomplete

class TerminalManager:
    terminal_in: Incomplete
    terminal_out: Incomplete
    ipc: Incomplete
    pipe_name: Incomplete
    running: bool
    threads: list[threading.Thread]
    def __init__(self, terminal_in: TerminalIn, terminal_out: TerminalOut, is_script: bool = True) -> None: ...
    def start(self, no_in: bool = False): ...
    def stop(self) -> None: ...
    def in_loop(self) -> None: ...
    def out_loop(self) -> None: ...
    def err_loop(self) -> None: ...
    def user_interaction(self, ipc: Ipc, cmd: str, timeout: float = 20, is_generator: bool = False): ...

class TerminalCommand:
    manager: Incomplete
    ipc: Incomplete
    cmd: Incomplete
    timeout: Incomplete
    terminal_in: Incomplete
    def __init__(self, manager: TerminalManager, ipc_slave: Ipc, cmd: str, timeout: float = 20) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
    def __iter__(self): ...
    def __next__(self): ...
