import paramiko
from .base import TerminalIn as TerminalIn, TerminalOut as TerminalOut
from .logger import logger as logger
from _typeshed import Incomplete
from typing import NoReturn

class CmdServer(TerminalIn, TerminalOut):
    process: Incomplete
    def __init__(self) -> None: ...
    @property
    def input(self) -> NoReturn: ...
    @input.setter
    def input(self, value) -> None: ...
    @property
    def out(self) -> str: ...
    @property
    def err(self) -> str: ...

class SshServer(TerminalIn, TerminalOut):
    client: Incomplete
    channel: Incomplete
    out_buffer: bytes
    err_buffer: bytes
    def __init__(self, ssh_client: paramiko.SSHClient, term: str, width: int, height: int) -> None: ...
    @property
    def input(self) -> NoReturn: ...
    @input.setter
    def input(self, value) -> None: ...
    @property
    def out(self) -> str: ...
    @property
    def err(self) -> str: ...
