import paramiko
import types
from ..core import Ipc as Ipc, SshServer as SshServer, TerminalCommand as TerminalCommand, TerminalManager as TerminalManager, logger as logger
from _typeshed import Incomplete
from pathlib import Path

class SshConnect:
    ssh_client: Incomplete
    ip: Incomplete
    port: Incomplete
    username: Incomplete
    def __init__(self, ip: str, port: int = 22, username: str = 'root') -> None: ...
    def password_connect(self, password: str): ...
    def private_key_connect(self, key_info: str, key_type: str, key_fmt: str, passphrase: str = None): ...
    def reconnect(self, method, authentication) -> None: ...

class SshExecutor:
    ssh_server: Incomplete
    terminal_manager: Incomplete
    def __init__(self, ssh_client: paramiko.SSHClient) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
    @property
    def input(self) -> None: ...
    @input.setter
    def input(self, value: str): ...
    def user_interaction(self, cmd: str, timeout: float = 20, is_generator: bool = False, ipc: Ipc = None): ...

class SshSession:
    terminal_in: Incomplete
    def __init__(self, ssh_executor: SshExecutor) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
    def cmd(self, cmd: str, timeout: float = 20): ...
    def download(self, local: Path, remote: str, timeout: float = 600): ...
    def upload(self, local: Path, remote: str, timeout: float = 600): ...
    def close(self) -> None: ...
