from .ssh import SshExecutor as SshExecutor, SshSession as SshSession

class SshTool(SshSession):
    def __init__(self, ssh_executor: SshExecutor) -> None: ...
    def ping(self, ip: str, count: int = 5, timeout: int = 3, debug: bool = False) -> tuple | bool: ...
    def easy_cmd(self, cmds) -> None: ...
